- name: "Register resource count"
  shell: python -c "print [x for x in range( 0, {{ res_def['count'] }} )]"
  register: res_count
  when: res_def['count'] is defined

- name: "provision/deprovision swift containers"
  os_object:
    auth:
      auth_url: "{{ endpoint }}" 
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project }}"
    container: "{{ res_def['res_name'] }}"
    container_access: "{{ res_def['access'] | default('private') }}"
    wait: yes
    state: "{{ state }}"
  when: res_def['count'] is not defined

- name: "provision/deprovision swift containers when count specified"
  os_object:
    auth:
      auth_url: "{{ container.0 }}" 
      username: "{{ container.1 }}"
      password: "{{ container.2 }}"
      project_name: "{{ container.3 }}"
    container: "{{ container.4 }}_{{ container.7 }}"
    container_access: "{{ container.5 }}"
    wait: yes
    state: "{{ container.6 }}"
  with_nested:
    - ["{{ endpoint }}"]
    - ["{{ username }}"]
    - ["{{ password }}"]
    - ["{{ project }}"]
    - ["{{ res_def['res_name'] }}"]
    - ["{{ res_def['access'] | default('private') }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: container
  register: res_def_output 
  when: res_def['count'] is defined and async == false

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_object: "{{ topology_outputs_os_object + res_def_output.results }}"
  when: async == false

- name: "Async:: provision/deprovision swift containers when count specified"
  os_object:
    auth:
      auth_url: "{{ container.0 }}"
      username: "{{ container.1 }}"
      password: "{{ container.2 }}"
      project_name: "{{ container.3 }}"
    container: "{{ container.4 }}_{{ container.7 }}"
    container_access: "{{ container.5 }}"
    wait: yes
    state: "{{ container.6 }}"
  with_nested:
    - ["{{ endpoint }}"]
    - ["{{ username }}"]
    - ["{{ password }}"]
    - ["{{ project }}"]
    - ["{{ res_def['res_name'] }}"]
    - ["{{ res_def['access'] | default('private') }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: container
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: res_def['count'] is defined and async == true

#- name: "Async: save the job id"
#  set_fact:
#    topology_job_ids: "{{ topology_job_ids + [ res_def_output ] }}"
#  when: async == true


# following tasks saves the async job details 
- name: "Async:: save the job id"
  set_fact:
    topology_outputs_os_object: "{{ topology_outputs_os_object + [ res_def_output ] }}"
  when: async == true
