#!/bin/bash -xe

# Verify inventory generation with template data
# distros.exclude: centos7 fedora26
# providers.include: dummy libvirt
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

function clean_up {
    set +e
    linchpin -w . -p PinFile.${PROVIDER}.yml -v destroy ${PROVIDER}-new
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspace

linchpin -w . -p PinFile.${PROVIDER}.yml -v up ${PROVIDER}-new

