#!/bin/bash -xe

# Verify that JsonInventoryFormatter produces valid json
# distros.exclude: none
# providers.include: dummy

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="dummy-new"
#CONFIG_FILE="../linchpin.conf"
TMP_FILE=$(mktemp)


function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/dummy/

ls

linchpin -w . -p "${PINFILE}" -v up --if json "${TARGET}" 2>&1 | tee -a ${TMP_FILE}

RC0=${?}

sed -i '$ d' ${TMP_FILE}
uhash=$(tail -n 1 ${TMP_FILE} | awk '{ print $3 }' )
echo ${uhash}

INVENTORY_FILE="./inventories/${TARGET}-${uhash}.inventory"
ls -l ./inventories
ls -l ${INVENTORY_FILE}

RC1=${?}

# count the number of hosts that were provisioned.  It should be four
LINES=$(cat ${INVENTORY_FILE} | jq  .all.hosts[] | wc -l)

if [ ${RC0} -eq 0 ] && [ ${RC1} -eq 0 ] && [ ${LINES} -eq 4 ]; then
    exit 0
else
    exit 1
fi
