#!/bin/bash -xe

# Verify that JsonInventoryFormatter produces valid json
# distros.exclude: none
# providers.include: dummy

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="dummy-new"
CONFIG_FILE="../linchpin.conf"
TMP_FILE=$(mktemp)


function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/dummy/

ls

linchpin -w . -p "${PINFILE}" -v up --if json "${TARGET}" 2>&1 | tee -a ${TMP_FILE}

INVENTORY_FOLDER="./inventories/"
INVENTORY_FILE=`ls -t1 $INVENTORY_FOLDER |  head -n 1`
echo $INVENTORY_FILE
grep "test" $INVENTORY_FOLDER/$INVENTORY_FILE
cat $INVENTORY_FOLDER/$INVENTORY_FILE
RC0=${?}

if [ ${RC0} -eq 0 ] ; then
    exit 0
else
    exit 1
fi
