#!/bin/bash -xe

# Verify distro selection in beaker
# distros.exclude: none
# providers.include: beaker
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="beaker-family"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . -v up "${TARGET}"
