#!/bin/bash -xe

# Verify distro selection in beaker
# distros.exclude: fedora29 centos7 fedora30 rhel8
# providers.include: beaker
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="beaker-multiple"
TMP_FILE=$(mktemp)
CONFIG_FILE="../linchpin.conf"

function clean_up {
    set +e
    linchpin -w . -v -c ${CONFIG_FILE} destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . -v -c ${CONFIG_FILE} up --inventory-format json "${TARGET}" 2>&1 | tee -a ${TMP_FILE}

RC0=${?}

# check inventory to make sure that we have the right number of lines
sed -i '$ d' ${TMP_FILE}
uhash=$(tail -n 1 ${TMP_FILE} | awk '{ print $3 }' )
echo ${uhash}

INVENTORY_FILE="./inventories/${TARGET}-${uhash}.inventory"
ls -l ./inventories
ls -l ${INVENTORY_FILE}

RC1=${?}

# expect two hosts in 'all' section of json
LINES=$(cat ${INVENTORY_FILE} | jq .all.hosts[] | wc -l)

if [ ${RC0} -eq 0 ] && [ ${RC1} -eq 0 ] && [ ${LINES} -eq 2 ]; then
    exit 0
else
    exit 1
fi
