#!/bin/bash -xe

# Verify os-server provisioning using inline template data
# distros.exclude: centos7 fedora29 fedora30 fedora31 rhel8
# providers.include: none

DISTRO=${1}
PROVIDER=${2}

TARGET="os-server-new"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" --template-data "${TEMPLATE_DATA}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . --template-data "${TEMPLATE_DATA}" --output-pinfile "${TMP_FILE}" -v up "${TARGET}"

grep "${DISTRO}" "${TMP_FILE}"
