#!/bin/bash -xe

# Verify os-server provisioning using file-based template data
# distros.exclude: none
# providers.include: openstack
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile.${PROVIDER}.yml"
TARGET="os-server-new"
TEMPLATE_FILE="./os-server-data.yml"
TMP_PF="/tmp/PinFile.${TARGET}.out"

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" --template-data "@${TEMPLATE_FILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM


pushd docs/source/examples/workspace
cat << EOF > "${TEMPLATE_FILE}"
---
distro: "${DISTRO}-"
EOF

cat "${TEMPLATE_FILE}"

linchpin -w . -p "${PINFILE}" --template-data "@${TEMPLATE_FILE}" --output-pinfile "${TMP_PF}" -v up "${TARGET}"

grep "${DISTRO}" "${TMP_PF}"
