#!/bin/bash -xe

# Verify os-server provisioning using file-based template data
# distros.exclude: centos7 fedora29 fedora30
# providers.include: openstack

DISTRO=${1}
PROVIDER=${2}

TARGET="os-server-new"
TEMPLATE_FILE="./os-server-data.yml"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . --template-data "@${TEMPLATE_FILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM


pushd docs/source/examples/workspaces/${PROVIDER}
cat << EOF > "${TEMPLATE_FILE}"
---
distro: "${DISTRO}-"
EOF

cat "${TEMPLATE_FILE}"

linchpin -w . --template-data "@${TEMPLATE_FILE}" --output-pinfile "${TMP_FILE}" -v up "${TARGET}"

grep "${DISTRO}" "${TMP_FILE}"
