#!/bin/bash -xe

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile.${PROVIDER}.yml"
TARGET="os-sg-new"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TMP_PF="/tmp/PinFile.${TARGET}.out"

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" --template-data "${TEMPLATE_DATA}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspace
linchpin -w . -p "${PINFILE}" --template-data "${TEMPLATE_DATA}" --output-pinfile "${TMP_PF}" -v up "${TARGET}"

grep "${DISTRO}" "${TMP_PF}"
