#!/bin/bash -xe

# Verify the openstack security group provisioning with template data
# distros.exclude: centos7
# providers.include: openstack
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="os-sg-new"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . --template-data "${TEMPLATE_DATA}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . --template-data "${TEMPLATE_DATA}" --output-pinfile "${TMP_FILE}" -v up "${TARGET}"

grep "${DISTRO}" "${TMP_FILE}"
