#!/bin/bash -xe

# Verify openstack heat provisioning
# distros.exclude: none
# providers.include: openstack
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="os_heat_target"
WORKSPACE_PATH="docs/source/examples/workspaces/openstack-heat/"

find / -name "*os_stack.yml"

function clean_up {
    set +e
    linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v destroy "${TARGET}"
    D_RC=0
    D_RC=(${?} -o ${D_RC})
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

# testing openstack heat workspace
echo "Testing os_heat workspace"
linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v up "${TARGET}"
