#!/bin/bash -xe

# Verify the openstack network provisioning with template data
# distros.exclude: centos7 fedora29 fedora30
# providers.include: openstack

DISTRO=${1}
PROVIDER=${2}

TARGET="os-network"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . -v up "${TARGET}"

# cleanup the network
linchpin -w . -v destroy "${TARGET}"
