#!/bin/bash -xe

# Verify openstack heat provisioning
# distros.exclude: fedora28 fedora29 fedora30
# providers.include: openstack
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
PINFILE="PinFile"
TARGET="os_heat_target"
WORKSPACE_PATH="docs/source/examples/workspaces/openstack-heat/"

function clean_up {
    set +e
    linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v destroy "${TARGET}"
    D_RC=0
    D_RC=(${?} -o ${D_RC})
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

# testing openstack heat workspace
echo "Testing os_heat workspace"
linchpin -w "${WORKSPACE_PATH}" --template-data "${TEMPLATE_DATA}" -p "${PINFILE}" -v up "${TARGET}"
