#!/bin/bash -xe

# Verify the openstack keypair provisioning
# distros.exclude: fedora29 fedora30  rhel8
# providers.include: openstack
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="os-keypair"
TMP_FILE=$(mktemp)

mkdir -p /root/.ssh

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . -v up "${TARGET}"

# cleanup the network
linchpin -w . -v destroy "${TARGET}"
