#!/bin/bash -xe

# Verify os-zone provisioning ( the test is currently disabled due to unavailable infra)
# distros.exclude: centos7 fedora29 fedora30 fedora31
# providers.include: none

DISTRO=${1}
PROVIDER=${2}

TARGET="os-recordset"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . -v up "${TARGET}"
