#!/bin/bash -xe

# Verify dummy provisioning using inline template data

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile.${PROVIDER}.yml"
TARGET="dummy-new"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"


function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" --template-data "${TEMPLATE_DATA}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

pushd docs/source/examples/workspace

linchpin -w . -p "${PINFILE}" --template-data "${TEMPLATE_DATA}" -v up "${TARGET}"

grep "${DISTRO}" /tmp/dummy.hosts

