#!/bin/bash -xe

# Verify dummy provisioning using file-based template data
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="dummy"
TEMPLATE_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . --template-data "@${TEMPLATE_FILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

cat << EOF > "${TEMPLATE_FILE}"
---
distro: "${DISTRO}-"
EOF

cat "${TEMPLATE_FILE}"

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

linchpin -w . --template-data "@${TEMPLATE_FILE}" -v up "${TARGET}"

grep "${DISTRO}" /tmp/dummy.hosts

