#!/bin/bash -xe

# Verify --no-hooks and --ignore-failed-hooks on dummy provider
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="dummy_target"
WORKSPACE_PATH="docs/source/examples/workspaces/dummy-hook-flags/"

function clean_up {
    set +e
    linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

# testing no-hooks flag
echo "Testing --no-hooks flag"
linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v up "${TARGET}" --no-hooks

# testing --ignore-failed-hooks flag
echo "Testing --ignore-failed-hooks flag"
linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v up "${TARGET}" --ignore-failed-hooks

grep "${DISTRO}" /tmp/dummy.hosts
