#!/bin/bash -xe

# Verify --no-hooks and --ignore-failed-hooks on dummy provider
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="dummy_target"


function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/workspace ]; then
    rm /tmp/workspace
fi

mkdir -p /tmp/workspace
pushd /tmp/workspace

linchpin fetch --dest /tmp/workspace https://github.com/samvarankashyap/linchpin_dummy_ws_hooks.git

# testing no-hooks flag
echo "Testing --no-hooks flag"
linchpin -w /tmp/workspace -p "${PINFILE}" -v up "${TARGET}" --no-hooks

# testing no-hooks flag
echo "Testing --ignore-failed-hooks flag"
linchpin -w /tmp/workspace -p "${PINFILE}" -v up "${TARGET}" --ignore-failed-hooks

grep "${DISTRO}" /tmp/dummy.hosts
