#!/bin/bash -xe

# Verify --no-hooks and --ignore-failed-hooks on dummy provider
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
TARGET="dummy_target"
WORKSPACE_PATH="docs/source/examples/workspaces/dummy-multi-file-hook/"

function clean_up {
    set +e
    linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v destroy "${TARGET}"
    D_RC=0
    D_RC=(${?} -o ${D_RC})
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

# testing no-hooks flag
echo "Testing multi file hook"
linchpin -w "${WORKSPACE_PATH}" -p "${PINFILE}" -v up "${TARGET}"

# fail if previous command fails
if [ ${?} -ne 0 ]; then
    exit ${?}
fi

if [ -e /tmp/ex_hook.txt ]; then
    rm /tmp/ex_hook.txt
fi
