#!/bin/bash -xe

# Verify --no-hooks and --ignore-failed-hooks on dummy provider
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
WORKSPACE_PATH="docs/source/examples/workspaces/dummy-external-hook"
TARGET="dummy_target"

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}" --use-shell
    D_RC=0
    D_RC=(${?} -o ${D_RC})
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

if [ -e /tmp/dummy.hosts ]; then
    rm /tmp/dummy.hosts
fi

pushd ${WORKSPACE_PATH}
pwd

# runs the linchpin up with --use-shell parameter
linchpin -w . -p "${PINFILE}" -v up "${TARGET}" --use-shell
