#!/bin/bash -xe

# Verify --no-hooks and --ignore-failed-hooks on dummy provider
# distros.exclude: none
# providers.include: dummy
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

PINFILE="PinFile"
WORKSPACE_PATH="docs/source/examples/workspaces/openstack-mock-workspace"
TARGET="all"

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy
    D_RC=0
    D_RC=(${?} -o ${D_RC})
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd ${WORKSPACE_PATH}
pwd

# Provision whole workspace using the mock data
linchpin -w . -p "${PINFILE}" -v up 
