---
# This playbook provisions given topology. 
- name:  "provisioning resources based on resource group type"
  hosts: localhost
  remote_user: root
  roles:
    - { role: 'common' }
 
- name:  "provisioning resources based on resource group type"
  hosts: localhost 
  remote_user: root
  roles:
    - { role: 'openstack', os_res_grps: "{{ os_res_grps }}" }
    - { role: 'aws', aws_res_grps: "{{ aws_res_grps  }}" }
    - { role: 'gcloud', gce_res_grps: "{{ gcloud_res_grps }}" }
