#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: none
# providers.include: libvirt
# providers.exclude: none

## NOTE: This is a temporary test to run libvirt tests until we fix
## the networking race condition. Tests will only run on centos7.

DISTRO=${1}
PROVIDER=${2}

TARGETS="${PROVIDER}-new"
TEST_NAME="${DISTRO}/${PROVIDER}/01_general"
DESCRIPTION="Test ${PROVIDER} provider with a simple up/destroy"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

TARGETS="libvirt-new"

pushd docs/source/examples/workspace

function clean_up {
    set +e
    D_RC=0
    for target in ${TARGETS}; do
        linchpin -w . -p PinFile.${PROVIDER}.yml -v destroy ${target}
        D_RC=(${?} -o ${D_RC})
    done
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

echo "CREDS_PATH: ${CREDS_PATH}"
for target in ${TARGETS}; do
    linchpin -w . -p PinFile.${PROVIDER}.yml -v up ${target}
done
