#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: centos7 fedora30 fedora31 rhel8
# providers.include: libvirt

## NOTE: This is a temporary test to run libvirt tests until we fix
## the networking race condition. Tests will only run on centos7.

set -o pipefail

DISTRO=${1}
PROVIDER=${2}

TEST_NAME="${DISTRO}/${PROVIDER}/02_libvirt-storage"
DESCRIPTION="Test ${PROVIDER} provider with storage provisioning"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

TARGET="libvirt-storage"

pushd docs/source/examples/workspaces/${PROVIDER}

function clean_up {
    set +e
    linchpin -w . -v destroy ${TARGET}
    # remove output file used to gen uhash if it exists
    rm storage.txt || true
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

linchpin -w . -v up ${TARGET} | tee -a storage.txt

cat storage.txt
uhash=$(grep ${TARGET} storage.txt | tail -n1 | cut -f3)
name="centos71-$uhash"
vm="${name}_0"

for f in $(virsh -c qemu:///system dumpxml $vm | grep "source file"); do
    if [[ $f = *${name}* ]]; then
        # make sure the file exists
        stat $(grep -o "'.*'" <<< $f | sed -e "s/'//g")
    fi
done

