#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: fedora28 centos7 fedora28
# providers.include: libvirt
# providers.exclude: none

## NOTE: This is a temporary test to run libvirt tests until we fix
## the networking race condition. Tests will only run on centos7.

set -o pipefail

DISTRO=${1}
PROVIDER=${2}

TEST_NAME="${DISTRO}/${PROVIDER}/03_libvirt-network"
DESCRIPTION="Test ${PROVIDER} provider with network provisioning"
NETWORK_NAME="linchpin-centos74"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

TARGET="libvirt-network"

pushd docs/source/examples/workspaces/${PROVIDER}

function clean_up {
    set +e
    # no clean up necessary because linchpin destroy is run as a a part of the
    # test
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

linchpin -w . -v up ${TARGET}

# if the network does not exist, this will fail
virsh net-list --all | grep ${NETWORK_NAME}

linchpin -w . -v destroy ${TARGET}

# if the still network exists, this will fail
virsh net-list --all | grep -v ${NETWORK_NAME}
