#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: centos7 fedora29 fedora31
# providers.include: none

## NOTE: This is a temporary test to run libvirt tests until we fix
## the networking race condition. Tests will only run on centos7.

set -o pipefail

DISTRO=${1}
PROVIDER=${2}

TEST_NAME="${DISTRO}/${PROVIDER}/04_libvirt-network-dns"
DESCRIPTION="Test ${PROVIDER} provider with network provisioning"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

TARGET="libvirt-network-dns"

pushd docs/source/examples/workspaces/${PROVIDER}

function clean_up {
    set +e
    linchpin -w . -v destroy ${TARGET}
    # remove output file used to gen uhash if it exists
    rm storage.txt || true
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

linchpin -w . -v up ${TARGET}
