#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: centos7 fedora30 fedora29
# providers.include: libvirt

## NOTE: This is a temporary test to run libvirt tests until we fix
## the networking race condition. Tests will only run on centos7.

set -o pipefail

DISTRO=${1}
PROVIDER=${2}

TEST_NAME="${DISTRO}/${PROVIDER}/06_libvirt-multi-node-network"
DESCRIPTION="Test ${PROVIDER} provider with multi-node-network provisioning"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

TARGET="libvirt-multi-node-net"

pushd docs/source/examples/workspaces/${PROVIDER}

function clean_up {
    set +e
    linchpin -w . -v destroy ${TARGET}
    # remove output file used to gen uhash if it exists
    rm resources/ -rf || true
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

linchpin -w . -v up ${TARGET} 
pushd resources/
IP_NUM=$(cat ${TARGET}.output|grep -o ip|wc -l)
if [ ${IP_NUM} -eq '6']; then
    echo "ip is returned incorretly"
    pushd ../
    exit 1
else
    pushd ../
    exit 0
fi
