#!/bin/bash -xe
  
# Verify the azure vm provisioning
# distros.exclude: none
# providers.include: azure
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET="azure_res_group"
pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . -vvv --template-data '{"profile": "sp", "distro": '${DISTRO}""'}' up "${TARGET}"
