#!/bin/bash -xe
  
# Verify the azure vm provisioning
# distros.exclude: fedora29 fedora30 centos7
# providers.include: azure
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET0="azure_vn"
TARGET1="azure_vn_subnet"
pushd docs/source/examples/workspaces/${PROVIDER}
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' destroy "${TARGET1}"
    linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' destroy "${TARGET0}"
    rm -rf resources/ inventories/
}

trap clean_up EXIT

linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' up "${TARGET0}"
linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' up "${TARGET1}"
