#!/bin/bash -xe
  
# Verify the azure vm provisioning
# distros.exclude: none
# providers.include: azure
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET0="azure_vn"
TARGET1="azure_vn_subnet"
pushd "docs/source/examples/workspaces/${PROVIDER}"
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "key"}' destroy "${TARGET1}"
    linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "key"}' destroy "${TARGET0}"
    rm -rf resources/ inventories/
}

trap clean_up EXIT

linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "key"}' up "${TARGET0}"
linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "key"}' up "${TARGET1}"
clean_up

linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "ad"}' up "${TARGET0}"
linchpin -w . -vvv --template-data '{ "distro": "'"${DISTRO}"'", "profile": "ad"}' up "${TARGET1}"
clean_up
