#!/bin/bash -xe
  
# Verify the azure vm provisioning
# distros.exclude: none
# providers.include: azure
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET="azure_multi_vm"
pushd "docs/source/examples/workspaces/${PROVIDER}"
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{"profile": "sp", "distro": '${DISTRO}""'}' destroy "${TARGET}"
    rm -rf resources/ inventories/
}

trap clean_up EXIT

linchpin -w . -vvv --template-data '{"profile": "sp", "distro": '${DISTRO}""'}' up "${TARGET}"
clean_up

linchpin -w . -vvv --template-data '{"profile": "ad", "distro": '${DISTRO}""'}' up "${TARGET}"
