#!/bin/bash -xe
  
# Verify the azure storage account provisioning
# distros.exclude: none
# providers.include: azure
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET="azure_storage_account"
pushd docs/source/examples/workspaces/${PROVIDER}
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' destroy "${TARGET}"
    rm -rf resources/ inventories/
}

trap clean_up EXIT

linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' up "${TARGET}"
