---
- name: "Set os_res_type value"
  set_fact:
    os_res_type: "{{ res_def['role'] }}"
  when: async

- name: "Add resource type to async_types"
  set_fact:
    async_types: "{{ async_types + [os_res_type] }}"
  when: async

- name: "Get the resource name"
  set_fact:
    os_resource_name: "{{ res_def['name'] }}"

- name: "Create name using uhash value"
  set_fact:
    os_resource_name: "{{ os_resource_name + '-' + uhash + '-' }}"
  when: enable_uhash

- name: "provision/teardown resources }}"
  include: "provision_{{ res_def['role'] }}.yml"
  when: res_def['role'] != 'os_server'

- name: "provision/teardown resources }}"
  include: "provision_os_server.yml"
  when: res_def['role'] == 'os_server' and res_def['auto_ip'] is not defined

- name: "provision/teardown resources }}"
  include: "provision_os_server-auto_ip.yml"
  when: res_def['role'] == 'os_server' and res_def['auto_ip'] is defined
