#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: none
# providers.include: none
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGETS="${PROVIDER}-new"
TEST_NAME="${DISTRO}/${PROVIDER}/01_general"
DESCRIPTION="Test ${PROVIDER} provider with a simple up/destroy"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"


if [ "${PROVIDER}" == "libvirt" ]; then
    TARGETS="libvirt-new" #libvirt-network"
elif [ "${PROVIDER}" == "openstack" ]; then
    TARGETS="os-server-new os-vol-new os-sg-new"
elif [ "${PROVIDER}" == "aws" ]; then
    TARGETS="aws-ec2-new" #aws-sg-new aws-s3-new aws-ec2-key-new
elif [ "${PROVIDER}" == "duffy" ]; then
    TARGETS="duffy-new" #aws-sg-new aws-s3-new aws-ec2-key-new
else
    TARGETS="dummy-new"
fi

pushd docs/source/examples/workspace

function clean_up {
    set +e
    for target in ${TARGETS}; do
        linchpin -w . -p PinFile.${PROVIDER}.yml -v destroy ${target}
    done
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

for target in ${TARGETS}; do
    echo "Target Name: ${target}"
    linchpin -w . -p PinFile.${PROVIDER}.yml -v up ${target}
done
