#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: none
# providers.include: none
# providers.exclude: libvirt

DISTRO=${1}
PROVIDER=${2}

TARGETS="${PROVIDER}-new"
TEST_NAME="${DISTRO}/${PROVIDER}/01_general"
DESCRIPTION="Test ${PROVIDER} provider with a simple up/destroy"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"



if [ "${PROVIDER}" == "libvirt" ]; then
    TARGETS="libvirt-new" #libvirt-network"
elif [ "${PROVIDER}" == "openstack" ]; then
    TARGETS="os-server-new os-sg-new" #os-vol-new 
elif [ "${PROVIDER}" == "aws" ]; then
    TARGETS="aws-ec2-new" #aws-sg-new aws-s3-new aws-ec2-key-new
elif [ "${PROVIDER}" == "beaker" ]; then
    TARGETS="beaker-new"
elif [ "${PROVIDER}" == "duffy" ]; then
    TARGETS="duffy-new"
else
    TARGETS="dummy-new"
fi

pushd docs/source/examples/workspace

function clean_up {
    set +e
    D_RC=0
    for target in ${TARGETS}; do
        linchpin -w . -p PinFile.${PROVIDER}.yml -v destroy ${target}
        D_RC=(${?} -o ${D_RC})
    done
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

echo "CREDS_PATH: ${CREDS_PATH}"
for target in ${TARGETS}; do
    linchpin -w . -p PinFile.${PROVIDER}.yml -vvvv up ${target}
done
