#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: none
# providers.include: none
# providers.exclude: libvirt

DISTRO=${1}
PROVIDER=${2}

TARGETS="${PROVIDER}-new"
TEST_NAME="${DISTRO}/${PROVIDER}/02-validate"
DESCRIPTION="Test ${PROVIDER} provider with a simple validate"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"



if [ "${PROVIDER}" == "libvirt" ]; then
    TARGETS="libvirt-new libvirt-network libvirt-storage"
elif [ "${PROVIDER}" == "openstack" ]; then
    TARGETS="os-server-new os-sg-new os-vol-new"
elif [ "${PROVIDER}" == "aws" ]; then
    TARGETS="aws-ec2-new aws-sg-new aws-s3-new aws-ec2-key-new"
elif [ "${PROVIDER}" == "beaker" ]; then
    TARGETS="beaker-new"
elif [ "${PROVIDER}" == "duffy" ]; then
    TARGETS="duffy-new"
elif [ "${PROVIDER}" == "openshift" ]; then
    TARGETS="openshift-new"
else
    TARGETS="dummy-new"
fi

pushd docs/source/examples/workspaces/${PROVIDER}

echo "CREDS_PATH: ${CREDS_PATH}"
for target in ${TARGETS}; do
    linchpin -w . -vvvv validate ${target}
done
