import com.cloudbees.plugins.credentials.Credentials

env.ghprbGhRepository = env.ghprbGhRepository ?: 'CentOS-PaaS-SIG/linchpin'
env.ghprbActualCommit = env.ghprbActualCommit ?: 'develop'
env.ghprbPullAuthorLogin = env.ghprbPullAuthorLogin ?: ''
env.ghprbPullId = env.ghprbPullId ?: ''

env.TARGET_BRANCH = env.TARGET_BRANCH ?: 'develop'

// Needed for podTemplate()
env.SLAVE_TAG = env.SLAVE_TAG ?: 'stable'
env.FEDORA28_TAG = env.FEDORA28_TAG ?: 'stable'
env.FEDORA29_TAG = env.FEDORA29_TAG ?: 'stable'
env.CENTOS7_TAG = env.CENTOS7_TAG ?: 'stable'

DOCKER_REPO_URL = env.DOCKER_REPO_URL ?: '172.30.254.79:5000'
// if LINCHPIN_PROVIDERS is defined in jenkins global
// environment this will limit the possible providers tested.
// if it's not defined you will get all the possible providers
// listed here.

LPROVIDERS = env.LINCHPIN_PROVIDERS ?: '__RELEASE__ dummy duffy libvirt aws'
PPROVIDERS = LPROVIDERS.tokenize()

TEST_PROVIDERS = env.TEST_PROVIDERS ?: '__RELEASE__ dummy duffy libvirt aws beaker openstack openshift'
TPROVIDERS = TEST_PROVIDERS.tokenize()

env.PROVIDERS = TPROVIDERS.intersect( PPROVIDERS ).join(" ")

OPENSHIFT_NAMESPACE = env.OPENSHIFT_NAMESPACE ?: 'continuous-infra'
OPENSHIFT_SERVICE_ACCOUNT = env.OPENSHIFT_SERVICE_ACCOUNT ?: 'jenkins'

// Execution ID for this run of the pipeline
executionID = UUID.randomUUID().toString()

// Pod name to use
c7podName = 'lp_centos7-' + executionID
f28podName = 'lp_fedora28-' + executionID
f29podName = 'lp_fedora29-' + executionID

def libraries = ['cico-pipeline' : ['master', 'https://github.com/CentOS/cico-pipeline-library.git'],
                 'ci-pipeline'   : ['master', 'https://github.com/CentOS-PaaS-SIG/ci-pipeline.git']]

libraries.each { name, repo ->
    library identifier: "${name}@${repo[0]}",
            retriever: modernSCM([$class: 'GitSCMSource',
                                  remote: repo[1]])
}

properties(
    [
        buildDiscarder(logRotator(artifactDaysToKeepStr: '30', artifactNumToKeepStr: '15', daysToKeepStr: '90', numToKeepStr: '15')),
        [$class: 'GithubProjectProperty', displayName: '', projectUrlStr: 'https://github.com/CentOS-PaaS-SIG/linchpin/'],
        disableConcurrentBuilds(),
        parameters(
            [
                string(defaultValue: 'develop',
                       description: '',
                       name: 'ghprbActualCommit'),
                string(defaultValue: '',
                       description: '',
                       name: 'sha1'),
                string(defaultValue: '',
                       description: 'Pull Request Number',
                       name: 'ghprbPullId'),
                string(defaultValue: '',
                       description: 'Pull Request Author username',
                       name: 'ghprbPullAuthorLogin'),
                string(defaultValue: '',
                       description: 'Git Hub Repository',
                       name: 'ghprbGhRepository'),
                string(defaultValue: 'stable',
                       description: 'Tag for slave image',
                       name: 'SLAVE_TAG'),
                string(defaultValue: 'stable',
                       description: 'Tag for fedora28 image',
                       name: 'FEDORA28_TAG'),
                string(defaultValue: 'stable',
                       description: 'Tag for fedora29 image',
                       name: 'FEDORA29_TAG'),
                string(defaultValue: 'stable',
                       description: 'Tag for centos7 image',
                       name: 'CENTOS7_TAG'),
                string(description: 'Providers to be tested',
                       name: 'TEST_PROVIDERS')
            ]
        ),
    ]
)

stage('Tests') {
    currentBuild.displayName = "Build#: ${env.BUILD_NUMBER} - PR: ${env.ghprbPullId} - Author: ${env.ghprbPullAuthorLogin}"
    if (env.ghprbActualCommit != null && env.ghprbActualCommit != "develop") {
        currentBuild.description = "<a href=\"https://github.com/${env.ghprbGhRepository}/pull/${env.ghprbPullId}\">PR #${env.ghprbPullId} (${env.ghprbPullAuthorLogin})</a>"
    }
    try {
        parallel (
            "centos7" : {
                pipelineUtils.clearTemplateNames()
                podTemplate(name: c7podName,
                            label: c7podName,
                            cloud: 'openshift',
                            serviceAccount: OPENSHIFT_SERVICE_ACCOUNT,
                            idleMinutes: 0,
                            namespace: OPENSHIFT_NAMESPACE,

                        containers: [
                            // This adds the custom slave container to the pod.
                            // Must be first with name 'jnlp'
                            containerTemplate(name: 'jnlp',
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/jenkins-continuous-infra-slave:' + SLAVE_TAG,
                                ttyEnabled: false,
                                args: '${computer.jnlpmac} ${computer.name}',
                                command: '',
                                workingDir: '/workDir'),
                            containerTemplate(name: 'centos7',
                                alwaysPullImage: true,
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/centos7:' + CENTOS7_TAG,
                                ttyEnabled: false,
                                command: '/usr/sbin/init',
                                privileged: true,
                                workingDir: '/workDir')
                        ],
                        volumes: [
                            emptyDirVolume(memory: false, mountPath: '/sys/class/net')
                        ]
                )
                {
                    execute_test(c7podName, "centos7")
                }
            }, fedora28: {
                pipelineUtils.clearTemplateNames()
                podTemplate(name: f28podName,
                            label: f28podName,
                            cloud: 'openshift',
                            serviceAccount: OPENSHIFT_SERVICE_ACCOUNT,
                            idleMinutes: 0,
                            namespace: OPENSHIFT_NAMESPACE,

                        containers: [
                            // This adds the custom slave container to the pod.
                            // Must be first with name 'jnlp'
                            containerTemplate(name: 'jnlp',
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/jenkins-continuous-infra-slave:' + SLAVE_TAG,
                                ttyEnabled: false,
                                args: '${computer.jnlpmac} ${computer.name}',
                                command: '',
                                workingDir: '/workDir'),
                            containerTemplate(name: 'fedora28',
                                alwaysPullImage: true,
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/fedora28:' + FEDORA28_TAG,
                                ttyEnabled: false,
                                command: '/usr/sbin/init',
                                privileged: true,
                                workingDir: '/workDir')
                        ],
                        volumes: [
                            emptyDirVolume(memory: false, mountPath: '/sys/class/net')
                        ]
                )
                {
                    execute_test(f28podName, "fedora28")
                }
            }, fedora29: {
                pipelineUtils.clearTemplateNames()
                podTemplate(name: f29podName,
                            label: f29podName,
                            cloud: 'openshift',
                            serviceAccount: OPENSHIFT_SERVICE_ACCOUNT,
                            idleMinutes: 0,
                            namespace: OPENSHIFT_NAMESPACE,

                        containers: [
                            // This adds the custom slave container to the pod.
                            // Must be first with name 'jnlp'
                            containerTemplate(name: 'jnlp',
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/jenkins-continuous-infra-slave:' + SLAVE_TAG,
                                ttyEnabled: false,
                                args: '${computer.jnlpmac} ${computer.name}',
                                command: '',
                                workingDir: '/workDir'),
                            containerTemplate(name: 'fedora29',
                                alwaysPullImage: true,
                                image: DOCKER_REPO_URL + '/' + OPENSHIFT_NAMESPACE + '/fedora29:' + FEDORA29_TAG,
                                ttyEnabled: false,
                                command: '',
                                privileged: true,
                                workingDir: '/workDir')
                        ],
                        volumes: [
                            emptyDirVolume(memory: false, mountPath: '/sys/class/net')
                        ]
                )
                {
                    execute_test(f29podName, "fedora29")
                }
            },
            failFast: true
        )
    } catch (e) {
        // Set build result
        currentBuild.result = 'FAILURE'

        // Report the exception
        echo e.getMessage()

        // Throw the error
        throw e

    }
}

def prepare_env() {
    dir('linchpin') {
        checkout([$class: 'GitSCM',
                  branches: [[name: env.ghprbActualCommit]],
                  doGenerateSubmoduleConfigurations: false,
                  extensions                       : [],
                  submoduleCfg                     : [],
                  userRemoteConfigs                : [
                          [refspec:
                                   '+refs/heads/*:refs/remotes/origin/*  +refs/pull/*:refs/remotes/origin/pr/* ',
                           url: "https://github.com/${env.ghprbGhRepository}"]
                  ]
        ])
        sh """
          git clone https://github.com/CentOS-PaaS-SIG/duffy-ansible-module.git
        """
        def creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
          com.cloudbees.plugins.credentials.Credentials.class
        );
        for (provider in PPROVIDERS) {
          def cf = creds.findResult { it.id == provider + '-key' ? it : null }
          if ( cf ) {
            println "found credential ${cf.id} filename:${cf.fileName}"
            withCredentials([file(credentialsId: provider + '-key', variable: 'FILEKEY')]) {
            sh """
                #!/bin/bash -x
                mkdir -p keys/
                cp ${FILEKEY} keys/${cf.fileName}
                chmod 0600 keys/${cf.fileName}
            """
            }
          }
        }
    }
}

def execute_test(String podname, String container) {
    node(podname) {
        try {
            def currentStage = container + "-prepare"
            stage(currentStage) {
                env.HOME = "/root"
                deleteDir()
                pipelineUtils.setDefaultEnvVars()
                // pipelineUtils.ocVerifyPod(env.NODE_NAME)
                prepare_env()
            }
            currentStage = container + "-install"
            stage(currentStage) {
                dir('linchpin') {
                  pipelineUtils.executeInContainer(currentStage,
                                                   container,
                                                   "./config/Dockerfiles/linchpin-install.sh")
                }
            }
            currentStage = container + "-test"
            stage(currentStage) {
                dir('linchpin') {
                  def vars = ["distro=${container}"]
                  pipelineUtils.executeInContainer(currentStage,
                                                   container,
                                                   "./config/Dockerfiles/linchpin-tests.sh",
                                                   vars)
                }
            }
        } finally {
            // pipelineUtils.ocGetContainerLogsFromPod(env.NODE_NAME)
            // Archive our artifacts
            step([$class: 'ArtifactArchiver',
                  allowEmptyArchive: true,
                  artifacts: '**/*_logs/**,*.txt,*.groovy,**/job.*,**/*.groovy,**/inventory.*,**/linchpin.latest',
                  excludes: '**/job.props,**/job.props.groovy,**/*.example',
                  fingerprint: true])
        }
    }
}
