#!/bin/bash -xe

# Verify os-server provisioning using inline template data
# distros.exclude: none
# providers.include: openshift
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="openshift-new"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"

function clean_up {
    set +e
    linchpin -w . -p "${PINFILE}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}
linchpin -w . -v up "${TARGET}"
