- name: "Register resource count"
  shell: python -c "print [x for x in range( 0, {{ res_def['count'] }} )]"
  register: res_count

- name: "Provision os_server resources by looping on count"
  os_server:
    state: "{{ instance.4 }}"
    auth:
      auth_url: "{{ instance.0 }}"
      username: "{{ instance.1 }}"
      password: "{{ instance.2 }}"
      project_name: "{{ instance.3 }}"
    name: "{{ instance.9 }}_{{ instance.10 }}_{{ instance.11 }}"
    image: "{{ instance.5 }}"
    key_name: "{{ instance.6  }}"
    api_timeout: 99999 
    flavor: "{{ instance.7 }}"
    network: "{{ instance.8 }}"
  with_nested:
    - ["{{ endpoint }}"]
    - ["{{ username }}"]
    - ["{{ password }}"]
    - ["{{ project }}"]
    - ["{{ state }}"]
    - ["{{ res_def['image'] }}"]
    - ["{{ res_def['keypair']  }}"]
    - ["{{ res_def['flavor']  }}"]
    - ["{{ res_def['networks'][0] }}"]
    - ["{{ res_grp_name }}"]
    - ["{{ res_def['res_name'] }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: instance
  when: res_def['res_type']=="os_server"
  register: res_def_output

- name: "set tmp var"
  set_fact:
    tmp: "{{ res_def_output.results }}"

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os: "{{ topology_outputs_os + tmp }}"

