---
- hosts: all
  gather_facts: false
  tasks:
    - name: debug
      debug:
        msg: "{{ default_ssh_key_path }}"
    - name: debug
      debug:
        msg: "{{ ansible_ssh_private_key_file }}"
    - name: set fact for default ssh args if not found
      set_fact:
        ansible_ssh_common_args: "{{ ansible_ssh_common_args | default('\'-o StrictHostKeyChecking=no\'') }}"
        ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python')  }}"
    - name: check the file path exists or not
      stat:
        path: "{{ ansible_ssh_private_key_file }}"
      register: stat_result
    - name: "search for the file in default path if not found"
      set_fact:
        ansible_ssh_private_key_file: "{{ default_ssh_key_path }}/{{ ansible_ssh_private_key_file }}"
      when: stat_result.stat.exists == False
    - name: ping task
      ping:
