#!/bin/bash -xe

# Verify the aws ec2 vpc subnet provisioning
# distros.exclude: centos7 fedora29 fedora30
# providers.include: aws

DISTRO=${1}
PROVIDER=${2}

TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TARGET="aws-ec2-vpc-subnet"

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . validate

linchpin -w . --template-data "${TEMPLATE_DATA}" -v up "${TARGET}"

