#!/bin/bash -xe

# Verify the aws ec2 elb lb provisioning
# distros.exclude: centos7 fedora28
# providers.include: aws
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="aws-ec2-elb-lb"

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

echo "add default profile in config"
mkdir -p ~/.aws/
printf "[default]\nregion = us-east-1" > ~/.aws/config

linchpin -w . -v up "${TARGET}"

