#!/bin/bash -xe

# Verify the aws ec2 elb lb provisioning
# distros.exclude: fedora29 fedora30 centos7
# providers.include: aws

DISTRO=${1}
PROVIDER=${2}
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"

TARGET="aws-ec2-elb-lb"

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

echo "add default profile in config"
mkdir -p ~/.aws/
printf "[default]\nregion = ca-central-1" > ~/.aws/config

linchpin -w . --template-data "${TEMPLATE_DATA}" -v up "${TARGET}"
