#!/bin/bash -xe

# Verify the aws-ec2 provisioning with template data
# distros.exclude: fedora29 fedora30 centos7 fedora31 rhel8
# providers.include: aws

DISTRO=${1}
PROVIDER=${2}

TARGET="aws-ec2-template"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . --template-data "${TEMPLATE_DATA}" -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . --template-data "${TEMPLATE_DATA}" -v up "${TARGET}"
