#!/bin/bash -xe

# Verify the openstack router provisioning
# distros.exclude: none
# providers.include: aws
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET0="aws-ec2-vpc-net"
TARGET1="aws-ec2-vpc-internet-gateway"
pushd docs/source/examples/workspaces/${PROVIDER}
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{ "vpc_id": '"${VPC_ID}"' }' destroy "${TARGET1}"
    linchpin -w . -v  destroy "${TARGET0}"
    rm -rf resources/
}

trap clean_up EXIT

linchpin -w . -v up "${TARGET0}"
VPC_ID=$(awk -F '"' '{print $64}' ./resources/ec2vpc.output)
#awk -F '"' '{print $64}' ./resources/ec2vpc.output|tee a.txt
linchpin -vvv --template-data '{ "vpc_id": '"${VPC_ID}"' }' up "${TARGET1}"
