#!/bin/bash -xe

# Verify the openstack router provisioning
# distros.exclude: fedora30 fedora31 centos7 centos8
# providers.include: aws
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}
TARGET="aws-ec2-vpc-gateway-test"
pushd docs/source/examples/workspaces/${PROVIDER}
function clean_up {
    set +e
    linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' destroy "${TARGET}"
    rm -rf resources/
}

trap clean_up EXIT

linchpin -w . -vvv --template-data '{ "distro": '${DISTRO}""'}' up "${TARGET}"
