#!/bin/bash -xe

# Verify the openstack router provisioning
# distros.exclude: centos7 fedora28
# providers.include: gcloud
# providers.exclude: none

DISTRO=${1}
PROVIDER=${2}

TARGET="gcloud-gce-eip"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . -v up "${TARGET}"
