#!/bin/bash -xe

# Verify basic provisioning for all supplied providers
# distros.exclude: centos7 fedora28
# providers.include: none

exit

DISTRO=${1}
PROVIDER=${2}

TEST_NAME="${DISTRO}/${PROVIDER}/01_general"
DESCRIPTION="Test ${PROVIDER} provider with a simple up/destroy"
TEMPLATE_DATA="{\"distro\": \"${DISTRO}-\"}"
TARGETS="gcloud-gce-new"

echo "Test Name: ${TEST_NAME}"
echo "${DESCRIPTION}"

ROOT="docs/source/examples/workspaces/${PROVIDER}"

function clean_up {
    set +e
    D_RC=0
    for target in ${TARGETS}; do
        linchpin -w ${PROVIDER} -v destroy ${target}
        D_RC=(${?} -o ${D_RC})
    done
    rm -rf ${PROVIDER}
    if [ ${D_RC} -ne 0 ]; then
        exit ${D_RC}
    fi
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

echo "CREDS_PATH: ${CREDS_PATH}"
for target in ${TARGETS}; do
    linchpin -w . fetch --root ${ROOT} --dest . --branch ${ghprbSourceBranch} https://github.com/${ghprbPullAuthorLogin}/linchpin
    linchpin -w ${PROVIDER} --template-data "${TEMPLATE_DATA}"  -vvvv up ${target}
done
