#!/bin/bash -xe

# Verify the gcloud compute engine provisioning
# distros.exclude: centos7
# providers.include: gcloud

DISTRO=${1}
PROVIDER=${2}

TARGET="gcloud-gce-new"
TMP_FILE=$(mktemp)

function clean_up {
    set +e
    linchpin -w . -v destroy "${TARGET}"
}
trap clean_up EXIT SIGHUP SIGINT SIGTERM

pushd docs/source/examples/workspaces/${PROVIDER}

linchpin -w . -vvvv up "${TARGET}"
