library('oasis-pipeline')

oasisMultistreamMoleculePipeline {
  upstream_git_url = 'https://github.com/oasis-roles/aws.git'
  molecule_role_name = 'aws'
  molecule_scenarios = ['docker']
  properties = [pipelineTriggers([cron('H H * * *')])]
}
